---
###############################################################################
# CentOS / RHEL
###############################################################################

- name: Install PostgreSQL PGDG repository (CentOS/RHEL)
  ansible.builtin.dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    disable_gpg_check: true
  when: ansible_os_family == "RedHat"

- name: Disable built-in PostgreSQL AppStream module (CentOS/RHEL)
  ansible.builtin.command: dnf -qy module disable postgresql
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Install PostgreSQL packages from PGDG (CentOS/RHEL)
  ansible.builtin.dnf:
    name:
      - "postgresql{{ opencast_postgresql_version }}-server"
      - "postgresql{{ opencast_postgresql_version }}"
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Initialise PostgreSQL database (CentOS/RHEL)
  ansible.builtin.command:
    cmd: "/usr/pgsql-{{ opencast_postgresql_version }}/bin/postgresql-{{ opencast_postgresql_version }}-setup initdb"
    creates: "/var/lib/pgsql/{{ opencast_postgresql_version }}/data/postgresql.conf"
  when: ansible_os_family == "RedHat"

- name: Set authentication to scram-sha-256 (CentOS/RHEL)
  ansible.builtin.lineinfile:
    path: "/var/lib/pgsql/{{ opencast_postgresql_version }}/data/postgresql.conf"
    regexp: '^#?password_encryption'
    line: "password_encryption = 'scram-sha-256'"
  notify: Restart Postgresql On CentOS
  when: ansible_os_family == "RedHat"

- name: Deploy custom pg_hba.conf (CentOS/RHEL)
  ansible.builtin.template:
    src: pg_hba.conf
    dest: "/var/lib/pgsql/{{ opencast_postgresql_version }}/data/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0644"
  notify: Restart Postgresql On CentOS
  when: ansible_os_family == "RedHat"

- name: Start and enable PostgreSQL (CentOS/RHEL)
  ansible.builtin.service:
    name: "postgresql-{{ opencast_postgresql_version }}"
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

###############################################################################
# Debian / Ubuntu
###############################################################################

- name: Ensure prerequisites for apt are installed (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Add PostgreSQL GPG key (Debian/Ubuntu)
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  when: ansible_os_family == "Debian"

- name: Add PostgreSQL repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: >-
      deb http://apt.postgresql.org/pub/repos/apt
      {{ ansible_distribution_release }}-pgdg main
    state: present
  register: add_postgres_repo
  when: ansible_os_family == "Debian"

- name: Update apt cache when repo added (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian" and add_postgres_repo.changed

- name: Install PostgreSQL (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - "postgresql-{{ opencast_postgresql_version }}"
      - "postgresql-client-{{ opencast_postgresql_version }}"
      - python3-psycopg2
      - acl
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Set auth to scram-sha-256 in postgresql.conf (Debian/Ubuntu)
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ opencast_postgresql_version }}/main/postgresql.conf"
    regexp: '^#?password_encryption'
    line: "password_encryption = 'scram-sha-256'"
  notify: Restart Postgresql On Debian/Ubuntu
  when: ansible_os_family == "Debian"

- name: Configure pg_hba.conf (Debian/Ubuntu)
  ansible.builtin.template:
    src: pg_hba.conf
    dest: "/etc/postgresql/{{ opencast_postgresql_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0644"
  notify: Restart Postgresql On Debian/Ubuntu
  when: ansible_os_family == "Debian"

- name: Ensure PostgreSQL is started and enabled (Debian/Ubuntu)
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

###############################################################################
# Common: create DB & user
###############################################################################

- name: Create PostgreSQL user
  become: true
  become_user: postgres
  become_method: ansible.builtin.su
  community.postgresql.postgresql_user:
    name: "{{ opencast_postgresql_user }}"
    password: "{{ opencast_postgresql_password }}"

- name: Create PostgreSQL database
  become: true
  become_user: postgres
  become_method: ansible.builtin.su
  community.postgresql.postgresql_db:
    name: "{{ opencast_postgresql_database }}"
    owner: "{{ opencast_postgresql_user }}"
