dependency:
  name: galaxy
  enabled: false

driver:
  name: containers

platforms:
  - name: opencast-postgresql-centos9
    image: quay.io/centos/centos:stream9
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: opencast-postgresql-debian
    image: docker.io/debian:latest
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: opencast-postgresql-ubuntu
    image: docker.io/ubuntu:latest
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint

provisioner:
  name: ansible

verifier:
  name: ansible
