---
- name: Verify PostgreSQL Installation
  hosts: all
  gather_facts: true
  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Ensure PostgreSQL service is running on RedHat/CentOS
      ansible.builtin.systemd:
        name: "postgresql-{{ opencast_postgresql_version }}"
        state: started
      when: ansible_os_family == "RedHat"

    - name: Ensure PostgreSQL service is running on Debian/Ubuntu
      ansible.builtin.systemd:
        name: postgresql
        state: started
      when: ansible_os_family == "Debian"

    - name: Get PostgreSQL version on RedHat/CentOS
      ansible.builtin.command: "/usr/pgsql-{{ opencast_postgresql_version }}/bin/psql --version"
      register: psql_version_centos
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Get PostgreSQL version on Debian/Ubuntu
      ansible.builtin.command: psql --version
      register: psql_version_debian
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Show PostgreSQL version on RedHat/CentOS
      ansible.builtin.debug:
        msg: "PostgreSQL version on {{ inventory_hostname }} (RedHat): {{ psql_version_centos.stdout }}"
      when: ansible_os_family == "RedHat"

    - name: Show PostgreSQL version on Debian/Ubuntu
      ansible.builtin.debug:
        msg: "PostgreSQL version on {{ inventory_hostname }} (Debian): {{ psql_version_debian.stdout }}"
      when: ansible_os_family == "Debian"
