---
name: lint

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: >
          pip install -r .dev_requirements.txt

      - run: yamllint --strict -c .yamllint .

      - run: ansible-lint
